--- #YAML:1.0
name:               NicToolServer
version:            2.08
abstract:           DNS management solution
author:
    - Damon Edwards, Abe Shelton, Greg Schueler, Matt Simerson
license:            affero-gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Apache2::SOAP:  0
    Apache::DBI:    0
    DBD::mysql:     2.0416
    DBI:            1.2
    Digest::HMAC:   0
    Digest::MD5:    0
    Net::IP:        0
    SOAP::Lite:     0.51
    XML::Parser:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
